# fly.toml app configuration file generated for micro-applications-template on 2023-04-27T20:52:21-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "micro-applications-template"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
